name: manfaa
description: "Manfaa - Choose your career with us!"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  go_router: ^14.2.1
  get_it: ^7.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  responsive_builder: ^0.7.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^6.0.3
  dio: ^5.5.0+1
  internet_connection_checker: ^1.0.0+1
  dio_retry_plus: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/core/config/localization/
    - assets/images/
    - assets/fonts/
    - assets/vectors/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
